app:
  name: "Tour Server API"
  version: "1.0.0"
  environment: "production"
  debug: false

server:
  host: "127.0.0.1"
  port: "1323"

database:
  host: "localhost"
  port: 5432
  user: "touruser"
  password: "tourpass123"
  dbname: "tourdb"
  sslmode: "disable"

jwt:
  secret: "712415f5ec16aee0df7f5882f2ef0c2cd9b8338bf0de32312e77b11d7828fec3"
  expiry_hour: 24
