package models

import "time"

// Inquiry is a lead generated by the call-to-action buttons
// ("Get a turnkey quote", "Calculate renovation costs", "Ask a question").
type Inquiry struct {
	ID            uint      `json:"id" gorm:"primaryKey"`
	CarID         *uint     `json:"carId"`
	RequestType   string    `json:"requestType" gorm:"not null"`
	ContactMethod string    `json:"contactMethod"`
	Phone         string    `json:"phone" gorm:"not null"`
	Name          string    `json:"name"`
	Message       string    `json:"message"`
	Status        string    `json:"status" gorm:"default:new"`
	CreatedAt     time.Time `json:"createdAt"`
}

func (Inquiry) TableName() string {
	return "inquiries"
}
